DROP TABLE `cond_platform`;
DROP TABLE `cond_country`;
DROP TABLE `cond_gender`;
DROP TABLE `platform`;
DROP TABLE `country`;
DROP TABLE `gender`;
DROP TABLE `advertisement_cond`;
DROP TABLE `cond`;
DROP TABLE `advertisement`;
