services:
  mysql:
    container_name: dcard_mysql
    image: mysql:8.0.36
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          memory: 1G

  redis:
    container_name: dcard_redis
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          memory: 1G
volumes:
  mysql_data: {}
