// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const checkCountry = `-- name: CheckCountry :one
SELECT COUNT(*)
FROM country
WHERE code = ?
`

func (q *Queries) CheckCountry(ctx context.Context, country string) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkCountry, country)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const checkGender = `-- name: CheckGender :one
SELECT COUNT(*)
FROM gender
WHERE code = ?
`

func (q *Queries) CheckGender(ctx context.Context, gender string) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkGender, gender)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const checkPlatform = `-- name: CheckPlatform :one
SELECT COUNT(*)
FROM platform
WHERE name = ?
`

func (q *Queries) CheckPlatform(ctx context.Context, platform string) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkPlatform, platform)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdvertisement = `-- name: CreateAdvertisement :execlastid
INSERT INTO advertisement (title, start_at, end_at)
VALUES (
        ?,
        ?,
        ?
    )
`

type CreateAdvertisementParams struct {
	Title   string    `json:"title"`
	StartAt time.Time `json:"start_at"`
	EndAt   time.Time `json:"end_at"`
}

func (q *Queries) CreateAdvertisement(ctx context.Context, arg CreateAdvertisementParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createAdvertisement, arg.Title, arg.StartAt, arg.EndAt)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createAdvertisementCondition = `-- name: CreateAdvertisementCondition :exec
INSERT INTO advertisement_cond (advertisement_id, cond_id)
VALUES (
        ?,
        ?
    )
`

type CreateAdvertisementConditionParams struct {
	AdvertisementID int32 `json:"advertisement_id"`
	ConditionID     int32 `json:"condition_id"`
}

func (q *Queries) CreateAdvertisementCondition(ctx context.Context, arg CreateAdvertisementConditionParams) error {
	_, err := q.db.ExecContext(ctx, createAdvertisementCondition, arg.AdvertisementID, arg.ConditionID)
	return err
}

const createCondition = `-- name: CreateCondition :execlastid
INSERT INTO cond (age_start, age_end)
VALUES (
        ?,
        ?
    )
`

type CreateConditionParams struct {
	AgeStart sql.NullInt32 `json:"age_start"`
	AgeEnd   sql.NullInt32 `json:"age_end"`
}

func (q *Queries) CreateCondition(ctx context.Context, arg CreateConditionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createCondition, arg.AgeStart, arg.AgeEnd)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createConditionCountry = `-- name: CreateConditionCountry :exec
INSERT INTO cond_country (cond_id, country_id)
VALUES (
        ?,
        (
            SELECT id
            FROM country
            WHERE code = ?
        )
    )
`

type CreateConditionCountryParams struct {
	ConditionID int32  `json:"condition_id"`
	Country     string `json:"country"`
}

func (q *Queries) CreateConditionCountry(ctx context.Context, arg CreateConditionCountryParams) error {
	_, err := q.db.ExecContext(ctx, createConditionCountry, arg.ConditionID, arg.Country)
	return err
}

const createConditionGender = `-- name: CreateConditionGender :exec
INSERT INTO cond_gender (cond_id, gender_id)
VALUES (
        ?,
        (
            SELECT id
            FROM gender
            WHERE code = ?
        )
    )
`

type CreateConditionGenderParams struct {
	ConditionID int32  `json:"condition_id"`
	Gender      string `json:"gender"`
}

func (q *Queries) CreateConditionGender(ctx context.Context, arg CreateConditionGenderParams) error {
	_, err := q.db.ExecContext(ctx, createConditionGender, arg.ConditionID, arg.Gender)
	return err
}

const createConditionPlatform = `-- name: CreateConditionPlatform :exec
INSERT INTO cond_platform (cond_id, platform_id)
VALUES (
        ?,
        (
            SELECT id
            FROM platform
            WHERE name = ?
        )
    )
`

type CreateConditionPlatformParams struct {
	ConditionID int32  `json:"condition_id"`
	Platform    string `json:"platform"`
}

func (q *Queries) CreateConditionPlatform(ctx context.Context, arg CreateConditionPlatformParams) error {
	_, err := q.db.ExecContext(ctx, createConditionPlatform, arg.ConditionID, arg.Platform)
	return err
}

const getActiveAdvertisements = `-- name: GetActiveAdvertisements :many
SELECT advertisement.id,
    title,
    start_at,
    end_at
FROM advertisement
WHERE advertisement.start_at < NOW()
    AND advertisement.end_at > NOW()
    AND NOT EXISTS (
        SELECT 1
        FROM advertisement_cond
        WHERE advertisement_cond.advertisement_id = advertisement.id
    )
UNION ALL
SELECT advertisement.id,
    title,
    start_at,
    end_at
FROM advertisement
WHERE advertisement.start_at < NOW()
    AND advertisement.end_at > NOW()
    AND EXISTS(
        SELECT 1
        FROM advertisement_cond
        WHERE (
                advertisement_cond.advertisement_id = advertisement.id
                AND advertisement_cond.cond_id IN (
                    SELECT DISTINCT cond.id
                    FROM cond
                        LEFT JOIN cond_gender ON cond.id = cond_gender.cond_id
                        LEFT JOIN cond_country ON cond.id = cond_country.cond_id
                        LEFT JOIN cond_platform ON cond.id = cond_platform.cond_id
                        LEFT JOIN gender ON cond_gender.gender_id = gender.id
                        LEFT JOIN country ON cond_country.country_id = country.id
                        LEFT JOIN platform ON cond_platform.platform_id = platform.id
                    WHERE (1 = 1)
                        AND (
                            ? IS NULL
                            OR (
                                (
                                    cond.age_start IS NULL
                                    OR cond.age_start <= ?
                                )
                                AND (
                                    cond.age_end IS NULL
                                    OR cond.age_end >= ?
                                )
                            )
                        )
                        AND(
                            ? IS NULL
                            OR (
                                gender.code IS NULL
                                OR ? = gender.code
                            )
                        )
                        AND(
                            ? IS NULL
                            OR (
                                country.code IS NULL
                                OR ? = country.code
                            )
                        )
                        AND(
                            ? IS NULL
                            OR (
                                platform.name IS NULL
                                OR ? = platform.name
                            )
                        )
                )
            )
    )
ORDER BY end_at ASC
LIMIT ?, ?
`

type GetActiveAdvertisementsParams struct {
	Age      sql.NullInt32  `json:"age"`
	Gender   sql.NullString `json:"gender"`
	Country  sql.NullString `json:"country"`
	Platform sql.NullString `json:"platform"`
	Offset   int32          `json:"offset"`
	Limit    int32          `json:"limit"`
}

func (q *Queries) GetActiveAdvertisements(ctx context.Context, arg GetActiveAdvertisementsParams) ([]Advertisement, error) {
	rows, err := q.db.QueryContext(ctx, getActiveAdvertisements,
		arg.Age,
		arg.Age,
		arg.Age,
		arg.Gender,
		arg.Gender,
		arg.Country,
		arg.Country,
		arg.Platform,
		arg.Platform,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Advertisement
	for rows.Next() {
		var i Advertisement
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.StartAt,
			&i.EndAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
